# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-15 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmazone',
            name='dma_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='zonetree',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='zonetree',
            name='zone_level',
            field=models.IntegerField(blank=True, choices=[(0, 'root'), (1, 'level 1'), (2, 'level 2'), (3, 'level 3'), (4, 'level 4')], null=True),
        ),
    ]
